### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Shiriow** [ReinaSakuraba/EO-Skill-Sim#8]
Shogun
Morale Boost is healing power and not static heal

Landsknecht
Vanguard is 5 turns all levels and only takes 1.5x extra damage 

Ninja
Ninpo:Flight level 9 - Evasion per dodge missing a %
Ninpo:Mirage is missing the defense value: 50/60/70/80/90/120%

Harbinger
Fatal Reap lvl 8 - Infliction rate missing a %

Sovereign
Attack Order lvl 7 - damage dealt missing a %
Guard Order lvl 7 - damage taken missing a %

Gunner
Leading Shot lvl 5 - 50% accuracy

Survivalist
Trick Step lvl 1 - 9,5% instead of 9.5%

Protector
Shield Rush
Speed missing a %

Highlander
Blood Fortune lvl8 - 5turns instead of 6

Also pretty sure I saw a % in a TP Cost part and also a Infliction Rate in a non ailment skill

**Comment by ReinaSakuraba** [comment]
All listed errors have been fixed. And there was indeed a % in the TP cost for Dismiss Revive and Atonement had Ailment Chance instead of Dispel Chance.
